In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
book = pd.read_csv(r'C:\Users\AMZAD\Pandas\codes\DataScienceProjects\RandomForest\Buy_Book.csv')
book

Age Student  Income    Savings Buy Book
0    43      No  median  Excellent      Yes
1    34     Yes    High       Fair      Yes
2    39     Yes  median       Fair      Yes
3    27     Yes     Low       Fair      Yes
4    44      No    High  Excellent      Yes
5    42      No  median       Fair       No
6    24     Yes    High       Fair      Yes
7    41      No  median       Fair      Yes
8    49      No    High       Fair       No
9    32     Yes    High       Fair      Yes
10   45     Yes     Low  Excellent       No
11   34      No  median  Excellent      Yes
12   21     Yes  median  Excellent      Yes
13   43      No  median  Excellent       No
14   28      No    High  Excellent       No
15   27     Yes     Low       Fair      Yes
16   46     Yes     Low  Excellent       No
17   42      No  median  Excellent      Yes
18   35      No  median  Excellent      Yes
19   38     Yes    High  Excellent      Yes
20   25      No  median       Fair       No
21   36      No    High  Excellent      Yes
22   32     Yes    High       High      Yes
23   49      No     Low       Fair       No
24   31     Yes  median       High      Yes

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
for column in book.columns:
    if book[column].dtype == type(object):
        le = LabelEncoder()
        book[column] = le.fit_transform(book[column])

In [6]:
book

Age  Student  Income  Savings  Buy Book
0    43        0       2        0         1
1    34        1       0        1         1
2    39        1       2        1         1
3    27        1       1        1         1
4    44        0       0        0         1
5    42        0       2        1         0
6    24        1       0        1         1
7    41        0       2        1         1
8    49        0       0        1         0
9    32        1       0        1         1
10   45        1       1        0         0
11   34        0       2        0         1
12   21        1       2        0         1
13   43        0       2        0         0
14   28        0       0        0         0
15   27        1       1        1         1
16   46        1       1        0         0
17   42        0       2        0         1
18   35        0       2        0         1
19   38        1       0        0         1
20   25        0       2        1         0
21   36        0       0        0         1
22   32        1       0        2         1
23   49        0       1        1         0
24   31        1       2        2         1

In [7]:
x = book.iloc[0:,0:4].values

In [8]:
y = book.iloc[0:,4].values

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.4,random_state=0)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
#n_estimator is how many trees we want to create in the Argument
model = RandomForestClassifier(n_estimators = 50)

In [13]:
model.fit(train_x,train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [14]:
pred_y = model.predict(test_x)

In [15]:
pred_y

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [16]:
test_y

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy = accuracy_score(test_y,pred_y)

In [19]:
accuracy

0.8

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
cn = confusion_matrix(test_y,pred_y)

In [22]:
cn

array([[2, 2],
       [0, 6]], dtype=int64)

In [23]:
#Templete

In [24]:
import numpy as np

In [25]:
value = np.array([[34,1,0,1]])

In [26]:
pred_value = model.predict(value)

In [27]:
pred_value

array([1])