# Naive Bayes:
* Navie Bayes is a supervised machine-learning algoithm that uses that Bayes Therom ,which asssumes that features are statically independent
* The therom relies on the navie assumption that input variable are independent of each ther,i,.e,there is no way anyhting about varabels when an additional variable

## Bayes Therom:
* is a therom based on a conditional probbility or in simple terms the 'likelyhood' that an event (A) will happen given that another event(B) has already happend  
   P(A/B) = P(B/A)P(A)/P(B)
* P(A/B): This is called posterior probabilty

# Maximum A Posterior(MAP) hypothesis
* The posterior probability for a no of diffrent hypothesis,we can select the hypothesis with highest probability
* This is the maximum probable hypothesis and may formally be called the maximum a posterior(MAP) hypothesis
* MAP(A) = max(P(A/B))

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Buy_Book.csv')
dataset.head()

Age Student  Income    Savings Buy Book
0   43      No  median  Excellent      Yes
1   34     Yes    High       Fair      Yes
2   39     Yes  median       Fair      Yes
3   27     Yes     Low       Fair      Yes
4   44      No    High  Excellent      Yes

* We have data set in a categorical form we need to conert into numerical from by using "LabelEncoder"

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
for column in dataset.columns:
    if dataset[column].dtype == type(object):
        le = LabelEncoder()
        dataset[column] = le.fit_transform(dataset[column])  

In [5]:
dataset.head()

Age  Student  Income  Savings  Buy Book
0   43        0       2        0         1
1   34        1       0        1         1
2   39        1       2        1         1
3   27        1       1        1         1
4   44        0       0        0         1

In [6]:
x = dataset.iloc[0:,0:4].values

In [7]:
y = dataset.iloc[0:,4].values

# Splitting Data set

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.5,random_state=0)

# Naive Bayes Model

In [10]:
#GaussianNB: we are having continues data in our Dataset
#Lets say we have split in our data set we use : "MultinomialNB"
#lets sat we have binary inour dataset set we introduse : "BernoulliNB"

In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
classifier = GaussianNB()

In [13]:
classifier.fit(train_x,train_y)

GaussianNB()

# Diffrence b/w test and predict values

In [14]:
#Predicted values
#Diffrence b/w actual and predicted values

In [15]:
pred_y = classifier.predict(test_x)

In [16]:
pred_y

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [17]:
test_y

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0])

# Model Selection

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [19]:
accuracy = accuracy_score(test_y,pred_y)

In [20]:
accuracy

0.6923076923076923

In [21]:
#Confusion_Matrix

In [22]:
confusion = confusion_matrix(test_y,pred_y)

In [23]:
confusion

array([[2, 4],
       [0, 7]], dtype=int64)

# Templete

In [24]:
import numpy as np

In [25]:
value = np.array([[50,0,0,0]])

In [26]:
pred_value = classifier.predict(value)

In [27]:
pred_value

array([1])