In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
book = pd.read_csv('Buy_Book.csv')
book.head()

Age Student  Income    Savings Buy Book
0   43      No  median  Excellent      Yes
1   34     Yes    High       Fair      Yes
2   39     Yes  median       Fair      Yes
3   27     Yes     Low       Fair      Yes
4   44      No    High  Excellent      Yes

In [3]:
book['Savings'].unique()

array(['Excellent', 'Fair', 'High'], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
for column in book.columns:
    if book[column].dtype == type(object):
        le = LabelEncoder()
        book[column] = le.fit_transform(book[column])

In [6]:
book.head()

Age  Student  Income  Savings  Buy Book
0   43        0       2        0         1
1   34        1       0        1         1
2   39        1       2        1         1
3   27        1       1        1         1
4   44        0       0        0         1

In [7]:
x = book.iloc[0:,0:4].values

In [8]:
y = book.iloc[0:,4].values

# Splitting Data

In [9]:
from sklearn.model_selection import train_test_split

In [14]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.2,random_state=0)

# Model Selection

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
model = DecisionTreeClassifier()

In [17]:
model.fit(train_x,train_y)

DecisionTreeClassifier()

# For predicting test_y values and diffrence b/w test and predicted "y" values

In [18]:
pred_y = model.predict(test_x)

In [19]:
pred_y

array([1, 1, 1, 0, 1])

# Accuracy

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy = accuracy_score(test_y,pred_y)

In [22]:
accuracy

0.8

# Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion = confusion_matrix(test_y,pred_y)

In [25]:
confusion

array([[1, 1],
       [0, 3]], dtype=int64)

# Templete

In [26]:
import numpy as np

In [27]:
value = np.array([[29,1,1,0]])

In [28]:
pred_value = model.predict(value)

In [29]:
pred_value

array([1])