In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
house = pd.read_csv('HousePrice2.csv')
house.head()

Area  No of Rooms  Age of House  Price 
0  2422            4            35   32500
1  2130            3            39   27000
2  1900            2            16   24000
3  3100            6            41   44000
4  2700            4            36   36000

In [3]:
x = house.iloc[0:17,:-1].values

In [4]:
x

array([[2422,    4,   35],
       [2130,    3,   39],
       [1900,    2,   16],
       [3100,    6,   41],
       [2700,    4,   36],
       [2900,    5,   21],
       [3200,    7,   24],
       [2800,    3,   36],
       [3000,    5,   40],
       [3300,    6,   29],
       [3150,    6,   25],
       [2325,    3,   34],
       [2250,    3,   40],
       [3330,    7,   31],
       [2850,    3,   31]], dtype=int64)

In [5]:
y = house.iloc[0:17,3].values

In [6]:
y

array([32500, 27000, 24000, 44000, 36000, 42000, 51000, 28000, 43000,
       47500, 49000, 29000, 29910, 49900, 27970], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.5,random_state=0)

In [9]:
from sklearn.tree import DecisionTreeRegressor

In [10]:
tree = DecisionTreeRegressor()
tree.fit(train_x,train_y)

DecisionTreeRegressor()

In [11]:
#tree.fit(test_x,test_y) no need to mention beacuse it casues error

In [12]:
pred_y = tree.predict(test_x)

In [13]:
pred_y

array([29910., 49000., 42000., 49000., 28000., 32500., 29000., 49000.])

In [14]:
x

array([[2422,    4,   35],
       [2130,    3,   39],
       [1900,    2,   16],
       [3100,    6,   41],
       [2700,    4,   36],
       [2900,    5,   21],
       [3200,    7,   24],
       [2800,    3,   36],
       [3000,    5,   40],
       [3300,    6,   29],
       [3150,    6,   25],
       [2325,    3,   34],
       [2250,    3,   40],
       [3330,    7,   31],
       [2850,    3,   31]], dtype=int64)

# Templete

In [15]:
import numpy as np

In [16]:
value = np.array([[2850,3,31]])

In [17]:
pred_y = tree.predict(value)

In [18]:
pred_y

array([28000.])